# Problem Statement - 1

### Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [4]:
import numpy as np
def powers(list_in,n,order):
    if order == 1:
        new_list = [[ele**i for i in range(n)] for ele in list_in]
    else:
        new_list=[[ele**i for i in range(n-1,-1,-1)] for ele in list_in]
    return np.asanyarray(new_list)

In [7]:
n = int(input("Enter the size of the list:"))
print("Enter the elements in the list")
list_in=[int(input()) for i in range(n)]
order =int( input("press 1 for increasing order or 0 for decreasing order:"))
print("The resultant matrix:\n",powers(list_in, n , order))

Enter the size of the list:5
Enter the elements in the list
1
2
3
4
5
press 1 for increasing order or 0 for decreasing order:0
The resultant matrix:
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [9]:
n = int(input("Enter the size of the list:"))
print("Enter the elements in the list")
list_in=[int(input()) for i in range(n)]
order =int( input("press 1 for increasing order or 0 for decreasing order:"))
print("The resultant matrix:\n",powers(list_in, n , order))

Enter the size of the list:3
Enter the elements in the list
1
2
3
press 1 for increasing order or 0 for decreasing order:1
The resultant matrix:
 [[1 1 1]
 [1 2 4]
 [1 3 9]]


# Problem Statement - 2

### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
### The moving average sequence has n-k+1 elements as shown below.
### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
### i 1 2 3 4 5 6 7 8 9 10
### ===== == == == == == == == == == ==
### Input 10 20 30 40 50 60 70 80 90 100 
### y1 25 = (10+20+30+40)/4
### y2 35 = (20+30+40+50)/4
### y3 45 = (30+40+50+60)/4
### y4 55 = (40+50+60+70)/4
### y5 65 = (50+60+70+80)/4
### y6 75 = (60+70+80+90)/4
### y7 85 = (70+80+90+100)/4
### Thus, the moving average sequence has n-k+1=10-4+1=7 values.
### Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [56]:
def moving_avgs(list_in,window=3):
    new_list=[]
    x=0
    for i in range(len(list_in)-window+1):
        if i != len(list_in)-window+1:
            avg=0
            for i in range(window):
                avg +=list_in[x+i]
            new_list.append(round(avg/window,2))
            x+=1
    return new_list

In [62]:
n = int(input("Enter the size of the list:"))
print("Enter the elements in the list")
list_in=[int(input()) for i in range(n)]
window = int(input("Enter the size of the window:"))
print("The Moving Average sequence with window size {} is".format(window))
print(moving_avgs(list_in,window))

Enter the size of the list:13
Enter the elements in the list
3
5
7
2
8
10
11
65
72
81
99
100
150
Enter the size of the window:3
The Moving Average sequence with window size 3 is
[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
